services:
  db:
    image: postgres:16
    container_name: postgres_ai_project
    restart: always
    environment:
      POSTGRES_DB: db-library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_ai_project
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com    # Email de login do pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin          # Senha de login do pgAdmin
    ports:
      - "5050:80"                              # Acessa pgAdmin em http://localhost:5050
    depends_on:
      - db                                     # Garante que o PostgreSQL suba primeiro
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge